### ISSUE TITLE
Upgrade Sentry SDK to newest version

### ISSUE THREAD

**Issue by vladanpaunovic** [robertcepa/toucan-js#100]
Sentry SDK has undergone some [important changes](https://github.com/getsentry/sentry-javascript/releases) over the past few months since version 6.19.6.

The breaking changes we introduced in v7 are minimal and easy to migrate. You can check the [migration docs here](https://github.com/getsentry/sentry-javascript/blob/master/MIGRATION.md#upgrading-from-6x-to-7x).

_By the way, I am from the Sentry SDK team and in case you need help migrating let me know._

**Comment by robertcepa** [comment]
[3.0.0](https://github.com/robertcepa/toucan-js/releases/tag/toucan-js%403.0.0 ) now uses the latest SDKs (v7.23.0).
