### ISSUE TITLE
Customizable "logger name"

### ISSUE THREAD

**Issue by zpg6** [robertcepa/toucan-js#102]
Great package! 👏

Unless there's a purpose "EdgeWorker" serves, would be nice if this were a configurable value. Especially since it appears in the Sentry Issues list.
 
https://github.com/robertcepa/toucan-js/blob/41d9c6b4f20a1acbf6063114aec9124d856f673e/src/index.ts#L379

Given maintainer approval on an option name, maybe even `logger: string;`, I'd be happy to contribute this change.

**Comment by robertcepa** [comment]
In [3.0.0](https://github.com/robertcepa/toucan-js/releases/tag/toucan-js%403.0.0 ), `logger` is no longer set to `EdgeWorker`.  

If you need to customized it, you can use `beforeSend` option:
```typescript
const sentry = new Toucan({
      dsn: env.SENTRY_DSN,
      context,
      request,
      beforeSend: (event) => {
        event.logger = 'my logger';
        return event;
      },
    });
```
