### ISSUE TITLE
scheduled waitUntil() don't report anything (maybe to typo in the README)

### ISSUE THREAD

**Issue by ismaail** [robertcepa/toucan-js#105]
From the README, passing a function to `context.waitUntil` don't seem to work.

```js
export default {
    async scheduled(controller: Controller, env: Env, context: Context) {
        //...
        context.waitUntil(async () => {
            try {
                // Your code
            } catch (err) {
                sentry.captureException(err);
            }
        });
    },
}
```

---

From [Cloudflare Documentation / ScheduledEvent / Syntax: Module Worker](https://developers.cloudflare.com/workers/runtime-apis/scheduled-event/#syntax-module-worker), the function passed to `context.waitUntil` must be called

```js
export default {
    async scheduled(event, env, ctx) {
        ctx.waitUntil(doSomeTaskOnASchedule());
    },
};
```

so the code that works:

```js
export default {
    async scheduled(controller: Controller, env: Env, context: Context) {
        //...
        context.waitUntil((async () => {
            try {
                // Your code
            } catch (err) {
                sentry.captureException(err);
            }
        })());
    },
}
```

---

- module (.mjs)
- wrangler 2.1.6
- node: v18.9.0
- OS: ArchLinux

**Comment by robertcepa** [comment]
Yeah it's a typo :) I'm preparing a big release soon, part of which will be updated documentation. Sorry for confusion!
