### ISSUE TITLE
configureScope does not work

### ISSUE THREAD

**Issue by MattIPv4** [robertcepa/toucan-js#108]
Calling `configureScope` seems to do absolutely nothing. Putting a log inside the callback results in nothing being logged.

Looking at the source, I don't see `configureScope` implemented at all, but I do see that the whole class is wrapped in a `Proxy`, which I suspect is suppressing errors you'd normally get for calling an undefined method.

**Comment by robertcepa** [comment]
This method is not supported. What is your use case? I am preparing a major release soon and might include it.

**Comment by MattIPv4** [comment]
I had expected to be able to use it given it exists in Sentry core (though given you expose all the scope setters in the class directly, it's less of an issue). I'm not too worried if you choose not to add it, but I'd be more concerned then that errors for unimplemented methods are being suppressed.

**Comment by robertcepa** [comment]
Thanks for filing! This should be fixed now in [3.0.0](https://github.com/robertcepa/toucan-js/releases/tag/toucan-js%403.0.0 )

Please reopen if this is still an issue.
