### ISSUE TITLE
`setFingerprint` no longer available in v3?

### ISSUE THREAD

**Issue by dotansimha** [robertcepa/toucan-js#115]
Hi,
I was using `setFingerprint` function to create a customer identifier for errors, but it seems like v3 removed this option (and it's not mentioned in the changelog?) 

Is there an alternative usage for setting the fingerprint of an exception reported? 

Thanks!

**Comment by robertcepa** [comment]
Hi, thanks for catching this! `setFingerprint` is available on `Scope`. There are multiple ways to set it:

Option 1:
```typescript
const sentry = new Toucan({
      dsn: env.SENTRY_DSN,
      context,
      request,
      initialScope: {
        fingerprint:  [...]
      }
    });
```

Option 2:
```typescript
const sentry = new Toucan({...});

sentry.configureScope(scope => scope.setFingerprint([...]))
```

Option 3:
```typescript
const sentry = new Toucan({...});

sentry.withScope((scope) => scope.setFingerprint([...]));
```

I'll update the changelog to reflect that.

**Comment by dotansimha** [comment]
Great, it seems to work :) Thank you!
