### ISSUE TITLE
sentry.startTransaction returns undefined

### ISSUE THREAD

**Issue by polRk** [robertcepa/toucan-js#122]
"toucan-js": "3.1.0"

```ts
const transaction = sentry.startTransaction({ name: 'Incoming request' })
// undefined
```

**Comment by kudlav** [comment]
Didn't you forget to import? @sentry/tracing?
```js
import { Toucan } from 'toucan-js';
import '@sentry/tracing';
```

**Comment by polRk** [comment]
> Didn't you forget to import? @sentry/tracing?
> 
> ```js
> import { Toucan } from 'toucan-js';
> import '@sentry/tracing';
> ```

Yes, i do. After adding it, works fine
