### ISSUE TITLE
Update sentry library version

### ISSUE THREAD

**Issue by polRk** [robertcepa/toucan-js#124]
https://github.com/robertcepa/toucan-js/blob/0ad38a13a0dd69ceedcf80faabf29a44866b711f/packages/toucan-js/package.json#L32-L34

Now last version is 7.40.0. I can't use because got conflicts with typings. And, for example, i can not use library version of sentry typings, because toucan doe not reexport them

**Comment by robertcepa** [comment]
Released in https://github.com/robertcepa/toucan-js/releases/tag/toucan-js%403.2.0
