### ISSUE TITLE
WithScope is ignored

### ISSUE THREAD

**Issue by AlexandrosGounis** [robertcepa/toucan-js#167]
Overwriting by using `withScope` does not work:

```ts
toucan.withScope(scope => {
   scope.setTag('ip', 'foo') // this works
   scope.setUser({ ip: 'foo' }) // this does not work
   scope.setTag('environment', 'dev') // this does not work

  // ...
  // captureEvent()
})
```

It looks like `environment` and user `ip` or `ip_address` cannot be overwritten. Is there a way to do that?

**Comment by robertcepa** [comment]
This is not an issue with `withScope`. Sentry backend by default infers IP out of request headers unless you toggle `Prevent Storing of IP Addresses` in your project settings. Let me know if that helped!
