### ISSUE TITLE
startTransaction() returns null

### ISSUE THREAD

**Issue by logemann** [robertcepa/toucan-js#168]
Hi,

why is startTransaction() returning null in this case? (sentry object works and is used in my app):

```
      const sentry = new Toucan({
         dsn: env.SENTRY_DSN,
         context,
         request,
      });

      const transaction = sentry.startTransaction({
         name: "Some Name",
      });
```

Do i need to import something besides the main Toucan package?

Thanks.

**Comment by AdiRishi** [comment]
Issue #122 seems related, did you try the suggested fix?

**Comment by robertcepa** [comment]
Assuming resolved
