### ISSUE TITLE
Possible to customize fetcher?

### ISSUE THREAD

**Issue by vlovich** [robertcepa/toucan-js#173]
I'd like to use my own transport fetch-like mechansim instead of global fetch. Would a PR making a change here be acceptable so that the fetch function can be injected as a transport option?

**Comment by robertcepa** [comment]
I opened https://github.com/robertcepa/toucan-js/pull/195 . Mind taking a look?

**Comment by robertcepa** [comment]
Released in https://github.com/robertcepa/toucan-js/releases/tag/toucan-js%403.2.0
