### ISSUE TITLE
Ability to disable / enable Sentry

### ISSUE THREAD

**Issue by vlovich** [robertcepa/toucan-js#183]
Right now, if I have a ToucanJS instance & I want to disable it, I have to add guard checks around it (or make it an `| undefined` type & invoke it through `?` safely). It would be convenient if the ToucanJS instance could be told to disable so that we would still have an instance against which we perform actions but the actual outbound fetches get disabled (& could be reenabled for completeness if needed). This was a confounding factor to some incidents.

**Comment by robertcepa** [comment]
Released in https://github.com/robertcepa/toucan-js/releases/tag/toucan-js%403.2.0
