### ISSUE TITLE
RewriteFrames from @sentry/integrations >= 7.74.0 is no longer compatible with toucan-js

### ISSUE THREAD

**Issue by olivierbeaulieu** [robertcepa/toucan-js#221]
Using from the `RewriteFrames` the latest `@sentry/integrations` no longer works. The integration's `processEvent` is never called.

I believe this is because of a recent refactoring from Sentry where the integration's `setupOnce` become a noop ([source](https://github.com/getsentry/sentry-javascript/commit/abd8b4d6a346cab55110cec83c15c1b0df3768c5#diff-a4ff2e44eaa9abef7ee53e9dd78fcc4fbc6d69eb450f0a59a768c57723e8f490R47))

Toucan depends on `setupOnce` calling the function that is passed to it, otherwise the event processor is never added to the SDK's scope ([source](https://github.com/robertcepa/toucan-js/blob/68c83695deed6f98728e3382087071f3736374f5/packages/toucan-js/src/integration.ts#L19C3-L24)).

**Comment by timfish** [comment]
If you use a version of `@sentry/integrations` that matches the the one in use in toucan-js ([ie. v7.76.0](https://github.com/robertcepa/toucan-js/blob/68c83695deed6f98728e3382087071f3736374f5/packages/toucan-js/package.json#L32)), you should not see this issue as the APIs will match.

Once [this auto-generated PR](https://github.com/robertcepa/toucan-js/pull/220/files) is merged and a release cut, you'll be able to use newer versions.

**Comment by olivierbeaulieu** [comment]
Aligning sentry versions didn't work for me. 

[RewriteFrames from v.7.76.0](https://github.com/getsentry/sentry-javascript/blob/7.76.0/packages/integrations/src/rewriteframes.ts#L46-L48) has the noop `setupOnce`, which toucan-js@3.3.1 [depends on](https://github.com/robertcepa/toucan-js/blob/toucan-js%403.3.1/packages/toucan-js/src/integration.ts#L19). Unless I'm misunderstanding something?

**Comment by timfish** [comment]
Ah yes sorry you are correct, I didn't realise `setupIntegrations` was overridden in the client. I guess this code need to be copied from Sentry core:
https://github.com/getsentry/sentry-javascript/blob/7303cdacb3ba2da1e71844e9daa5ffdb91d9a8a7/packages/core/src/integration.ts#L106-L130

**Comment by maciejp-ro** [comment]
Bumped into this as well – took me more than a day of trying to figure it out on Dec 8, a few days before this issue was filed; resumed that work today and found this, thank you for reporting!

FYI the title should be ">= 7.74.0" or "> 7.73.0" – 7.74.0 is the first version with noop `setupOnce`.

With `yarn`, the following override in `package.json` makes it work:

```json
  "resolutions": {
    "toucan-js/@sentry/core": "7.73",
    "toucan-js/@sentry/integrations": "7.73",
    "toucan-js/@sentry/types": "7.73",
    "toucan-js/@sentry/utils": "7.73"
  }
```

**Comment by olivierbeaulieu** [comment]
Issue title updated, good catch.

**Comment by robertcepa** [comment]
Sentry removed class-based integrations in v8. We just released a new version of Toucan that uses new function-based integrations in https://github.com/robertcepa/toucan-js/releases/tag/toucan-js%404.0.0

Upgrading to v4.0.0 should resolve this problem. Note that `RewriteFrames` is now called `rewriteFramesIntegration`.
