### ISSUE TITLE
Sentry Hub has been deprecated in since version 7.110.0

### ISSUE THREAD

**Issue by Soviut** [robertcepa/toucan-js#232]
According to these docs the Hub object that Toucan's main class extends has been deprecated since Sentry v7.110.0

https://docs.sentry.io/platforms/javascript/migration/v7-to-v8/v7-deprecations/#deprecate-hub

I'm using Hono with `@hono/sentry` that integrates Toucan and the following both yield deprecation warnings

```typescript
c.get('sentry').setContext({ ... })
c.get('sentry').captureException(err)
```

How can we access the new Sentry object? Should Toucan be extending the new Sentry object? Should we use `@sentry/node`?

**Comment by robertcepa** [comment]
Will be patched in the next version. Thanks for raising.

**Comment by timfish** [comment]
I'm working on a PR to update to v8 of the Sentry libs

**Comment by robertcepa** [comment]
Released in https://github.com/robertcepa/toucan-js/releases/tag/toucan-js%404.0.0

**Comment by cosbgn** [comment]
Can someone guide me on how to do this with toucan v4:

```
const sentry = new Toucan({
    dsn: process.env.RISPOSE_SENTRY_DNS,
    context: context.event,
})
sentry.~~setTag~~('server', true)
sentry.~~captureException~~(err)
});
```

Both `setTag` and `captureException` are marked as `@deprecated — Use Sentry.captureException() instead.` not sure how to do that with toucan now
