### ISSUE TITLE
Add support for sampling

### ISSUE THREAD

**Issue by pims** [robertcepa/toucan-js#46]
The [official Sentry documentation](https://docs.sentry.io/error-reporting/configuration/?platform=browser) states:

> sampleRate
> Configures the sample rate as a percentage of events to be sent in the range of 0.0 to 1.0. The default is 1.0 which means that 100% of events are sent. If set to 0.1 only 10% of events will be sent. Events are picked randomly.

It would be very valuable to make this a configurable option in `toucan-js`.

**Comment by robertcepa** [comment]
Added in https://github.com/robertcepa/toucan-js/releases/tag/v2.2.0
