### ISSUE TITLE
Support for ScheduledEvent/cron triggers?

### ISSUE THREAD

**Issue by johnsheehan** [robertcepa/toucan-js#55]
Any plans to add support for cron triggers that use ScheduledEvent instead of FetchEvent?

**Comment by robertcepa** [comment]
Yep, will support Durable Objects too. Hoping to get a chance this weekend.

**Comment by robertcepa** [comment]
https://github.com/robertcepa/toucan-js/releases/tag/v2.3.0

Will do Durable Objects separately.

**Comment by johnsheehan** [comment]
🙏🙏🙏
