### ISSUE TITLE
Durable Objects and modules

### ISSUE THREAD

**Issue by robertcepa** [robertcepa/toucan-js#65]
Just wanted to give a heads up that Durable Objects and standard Workers written as modules is on my radar, but there are still many moving pieces in BETA and so I don't want to rush this. I'm expecting breaking changes in how `toucan-js` is going to consume event properties like `waitUntil` or `request` in mjs world.

**Comment by robertcepa** [comment]
As a workaround, I believe that you might still be able to get `toucan-js` working in Durable Objects BETA, but you'll need to build `event` object manually and also override the `event` type if you use TypeScript. 

```
export class MyDurableObject {
    constructor(state, env) {
        this.state = state;
    }

    async fetch(request) {
        this.sentry = new Toucan({
          event: {
            waitUntil: this.state.waitUntil.bind(this.state),
            request
          } as any,
          // ... other opts
        });
    
        ...
    }
}
```

**Comment by tyvdh** [comment]
https://community.cloudflare.com/t/2021-4-15-workers-runtime-release-notes/261917

```
waitUntil is now supported for module workers. An additional argument called ‘ctx’ is passed after ‘env’, and waitUntil is a method on ‘ctx’.
```

Should be able to get this fully working natively now!

**Comment by tyvdh** [comment]
Note that durable objects themselves have had `waitUntil` for awhile now, it's the es modules that haven't until a couple days ago.

<img width="688" alt="Screen Shot 2021-04-20 at 8 37 05 PM" src="https://user-images.githubusercontent.com/4383610/115480321-3fe7c200-a218-11eb-9d23-8f6fc711f672.png">

https://developers.cloudflare.com/workers/runtime-apis/durable-objects

**Comment by robertcepa** [comment]
Just published https://github.com/robertcepa/toucan-js/releases/tag/v2.5.0-beta.1

**Comment by tyvdh** [comment]
Just implemented. Looks like it's working great! Will keep an eye on it and report anything I see,
