### ISSUE TITLE
setExtras shallow merges objects (doc)

### ISSUE THREAD

**Issue by ptim** [robertcepa/toucan-js#91]
Hi! Thanks for Toucan 🙏

I've found that setExtras shallow merges objects - and on investigation, confirmed that this is also the case in @sentry/core: https://github.com/getsentry/sentry-javascript/blob/master/packages/hub/src/hub.ts#L313 

I tested this in a fork, and proposed a changed to the Toucan docs, but this issue may be enough - merging the PR might be unnecessary - whatever!

Test and suggested readme change: [ptim/toucan-js/pull/1](https://github.com/ptim/toucan-js/pull/1/files#diff-b335630551682c19a781afebcf4d07bf978fb1f8ac04c6bf87428ed5106870f5)

**Comment by robertcepa** [comment]
[3.0.0](https://github.com/robertcepa/toucan-js/releases/tag/toucan-js%403.0.0 ) now extends `Hub` from `@sentry/core`. So whatever the `@sentry/core` package is doing is also going to be the case in `toucan-js`.
